name: CTF
author: Vedarth & Karen
version: 1.2
main: me.vv.ctf.Main
commands:
  setteam:
    aliases: st
  teams:
  setflagspawn:
    aliases: sfs
  cmdtoggle:
    aliases: cmtg
  respawntime:
    aliases: rt
